version: '2'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    container_name: gitlab-ce
    # hostname: 'gitlab.zzjz.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # external_url 'https://gitlab.zzjz.com'
        external_url 'http://192.168.11.115'
        gitlab_rails['gitlab_ssh_host'] = '192.168.11.115'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '8989:80'
      - '4443:443'
      - '2224:22'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

volumes: 
  gitlab_config:
  gitlab_logs:
  gitlab_data:
