version: '3'
services:
    gitlab-runner:
      image: 'gitlab/gitlab-runner'
      container_name: gitlab-runner
      restart: always
      networks:
        - gitlab_default
      volumes:
        - /opt/zzjz/gitlab-runner/config:/etc/gitlab-runner
        - /var/run/docker.sock:/var/run/docker.sock
networks:
  gitlab_default:
    external: true