version: '3.4'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    restart: always
    ports:
      - '8787:8080'
      - '50000:50000'
    volumes:
      - '/opt/zzjz/jenkins:/var/jenkins_home'