# Please refer https://docs.docker.com/compose to learn more about Docker Compose.

# This is a sample docker-compose file with two services
# 1. yourwebapp is an sample web service where the docker container image will be built from the Dockerfile as
#    part of starting the compose.
# 2. redis is an existing image hosted in docker hub.
version: '3.4'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports: 
      - '9000:9000'
      - '8000:8000'
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes: 
  portainer_data:
